# Generated by Django 4.2.8 on 2024-02-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('camera_equipment', models.TextField()),
                ('lens_used', models.TextField()),
                ('hourly_charges', models.CharField(max_length=50)),
                ('events_covered', models.TextField()),
            ],
        ),
    ]
